# Generated by Django 5.2.12 on 2026-04-11 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(verbose_name='Позиция')),
                ('image', models.ImageField(upload_to='tests/images/', verbose_name='Изображение')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('done', 'Завершено')], default='pending', max_length=10, verbose_name='Статус')),
                ('total_views', models.PositiveIntegerField(default=0, verbose_name='Всего показов')),
                ('total_clicks', models.PositiveIntegerField(default=0, verbose_name='Всего кликов')),
                ('baseline_views', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baseline просмотров')),
                ('baseline_clicks', models.PositiveIntegerField(blank=True, null=True, verbose_name='Baseline кликов')),
                ('rounds_passed', models.PositiveIntegerField(default=0, verbose_name='Сколько кругов прошла картинка')),
                ('wins_count', models.PositiveIntegerField(default=0, verbose_name='Счётчик побед')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало показа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_id', models.BigIntegerField(verbose_name='ID кампании WB')),
                ('product_id', models.BigIntegerField(verbose_name='ID товара (Артикул)')),
                ('name', models.CharField(max_length=255, verbose_name='Название теста')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'На паузе'), ('finished', 'Завершён')], default='draft', max_length=10, verbose_name='Статус')),
                ('error_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ошибка теста')),
                ('impressions_per_cycle', models.PositiveIntegerField(verbose_name='Показов на цикл')),
                ('max_impressions_per_image', models.PositiveIntegerField(verbose_name='Макс. показов на изображение')),
                ('time_per_cycle', models.PositiveIntegerField(verbose_name='Время на цикл (сек)')),
                ('current_views', models.PositiveIntegerField(default=0, verbose_name='Показов на текущий момент')),
                ('current_cycle', models.PositiveIntegerField(default=0, verbose_name='Номер цикла')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Статус обработки теста за проход')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата старта')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('current_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='stats.image', verbose_name='Текущее изображение')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='ImageShowStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_number', models.PositiveIntegerField(verbose_name='Номер цикла')),
                ('start_views', models.PositiveIntegerField(verbose_name='Показы на старте')),
                ('start_clicks', models.PositiveIntegerField(verbose_name='Клики на старте')),
                ('started_at', models.DateTimeField(verbose_name='Время старта')),
                ('end_views', models.PositiveIntegerField(verbose_name='Показы на конце')),
                ('end_clicks', models.PositiveIntegerField(verbose_name='Клики на конце')),
                ('finished_at', models.DateTimeField(verbose_name='Время завершения')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.image', verbose_name='Изображение')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stats.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Сеанс показа изображения',
                'verbose_name_plural': 'Сеансы показа изображений',
            },
        ),
        migrations.AddField(
            model_name='image',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='stats.test', verbose_name='Тест'),
        ),
        migrations.CreateModel(
            name='WBToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='WB токен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wb_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'WB токен',
                'verbose_name_plural': 'WB токены',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='wb_token',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='stats.wbtoken', verbose_name='WB токен'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['test', 'status'], name='stats_image_test_id_4bc868_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['test', 'position'], name='stats_image_test_id_6e5ea7_idx'),
        ),
        migrations.AddConstraint(
            model_name='image',
            constraint=models.UniqueConstraint(fields=('test', 'position'), name='unique_test_position'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['status'], name='stats_test_status_81a90c_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['user'], name='stats_test_user_id_0377bc_idx'),
        ),
    ]
