# Generated by Django 5.2.12 on 2026-04-13 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_alter_imageshowstat_nullable_end_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='error_text',
        ),
        migrations.AddField(
            model_name='image',
            name='date_baseline',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время снимка'),
        ),
        migrations.AddField(
            model_name='test',
            name='error_counts',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество ошибочных запусков'),
        ),
        migrations.AddField(
            model_name='test',
            name='error_log',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='last_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('paused', 'На паузе'), ('finished', 'Завершён'), ('error', 'Ошибка')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='CampaignDailyStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата (WB timezone)')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Показы за день')),
                ('clicks', models.PositiveIntegerField(default=0, verbose_name='Клики за день')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='stats.test', verbose_name='Тест')),
            ],
            options={
                'verbose_name': 'Дневная статистика изображения',
                'verbose_name_plural': 'Дневная статистика изображений',
            },
        ),
        migrations.AddField(
            model_name='imageshowstat',
            name='end_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='end_sessions', to='stats.campaigndailystat'),
        ),
        migrations.AddField(
            model_name='imageshowstat',
            name='start_day',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start_sessions', to='stats.campaigndailystat'),
        ),
        migrations.AddConstraint(
            model_name='imageshowstat',
            constraint=models.UniqueConstraint(condition=models.Q(('finished_at__isnull', True)), fields=('image',), name='unique_open_session_per_image'),
        ),
        migrations.AddIndex(
            model_name='campaigndailystat',
            index=models.Index(fields=['test', 'date'], name='stats_campa_test_id_31f7c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='campaigndailystat',
            constraint=models.UniqueConstraint(fields=('test', 'date'), name='unique_test_date'),
        ),
    ]
