# Generated by Django 5.2.12 on 2026-04-13 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_remove_test_error_text_image_date_baseline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_round', models.PositiveBigIntegerField(default=1, verbose_name='Текущий раунд планировщика')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Состояние планировщика',
                'verbose_name_plural': 'Состояния планировщика',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='processed_round',
            field=models.PositiveBigIntegerField(db_index=True, default=0, verbose_name='Номер раунда планировщика, в котором тест уже обработан'),
        ),
        migrations.AddField(
            model_name='test',
            name='processing_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Срок действия lease-lock на обработку'),
        ),
        migrations.AddField(
            model_name='test',
            name='processing_owner',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, verbose_name='Идентификатор воркера, который удерживает обработку'),
        ),
    ]
