# Generated by Django 5.2.12 on 2026-04-15 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0004_schedulerstate_test_processed_round_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='processing_expires_at',
        ),
        migrations.RemoveField(
            model_name='test',
            name='processing_owner',
        ),
        migrations.AddField(
            model_name='test',
            name='set_pause',
            field=models.BooleanField(default=False, verbose_name='Флаг для установки на паузу'),
        ),
    ]
