# Generated by Django 5.2.12 on 2026-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_remove_test_processing_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wbtoken',
            name='token',
            field=models.CharField(max_length=500, verbose_name='WB токен'),
        ),
    ]
