# Generated by Django 5.2.12 on 2026-05-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0006_alter_wbtoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='rotation_forward',
            field=models.BooleanField(default=True, verbose_name='Направление ротации'),
        ),
    ]
